### PR TITLE
Fix for compatibility with SUPEE-8788

### PR DESCRIPTION
**Pull request by unxsist**
The SUPEE-8788 patch adds a new uploader which removes Flash from the admin catalog image upload functionality. Because CreareSEO overrides the template, the uploader is broken after applying the patch. I've adjusted the template to incorporate the patch adjustments.

### CODE REVIEW

**Comment by infabo** [comment]
+1

**Comment by ebabis** [comment]
+1

**Comment by AndreKelling** [comment]
+1

**Comment by immist** [comment]
thank you @unxsist!

**Comment by krillo** [comment]
+1

**Comment by infabo** [comment]
@krillo Thanks for the upvote, but this PR was already merged on 26 Oct 2016 😄

**Comment by krillo** [comment]
Hi,

Well, I patched an old Magento site and have no idea which modules they
have or if there out of date. So your patch saved my day :)
Thanks - Kristian

**Pull request merged**
