### PR TITLE
Translate CreareSEO to pt_BR

### PR DESCRIPTION
**Pull request by mariovalney**
Translating the config labels can help brazilian users.

### CODE REVIEW

**Comment by sprankhub** [comment]
Thanks for your PR!

**Comment by mariovalney** [comment]
I guess this feature is not to override but to be sure we will keep our translation for our module avoiding conflict.

But ok. We can remove.

**Comment by mariovalney** [comment]
Done :smiley:

**Comment by sprankhub** [comment]
Thanks, man!

**Pull request merged**
